// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "2f803e7e-a0e0-46d6-8e4c-1d69d24a8524";

const char SSID[]               = "hcn sar 03212323255";    // Network SSID (name)
const char PASS[]               = "";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "znCV25MF4UG@yzRo0e00!Z@QI";    // Secret device password

void onFanButtonChange();
void onServoButtonChange();
void onWetnessChange();

float humidity;
float temperature;
bool fan_button;
bool servo_button;
bool wetness;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(fan_button, READWRITE, ON_CHANGE, onFanButtonChange);
  ArduinoCloud.addProperty(servo_button, READWRITE, ON_CHANGE, onServoButtonChange);
  ArduinoCloud.addProperty(wetness, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
